server:
  host: 127.0.0.1
  port: 8080
  timeout:
    server: "30s"
    read: "15s"
    write: "10s"
    idle: "5s"


XApiKey: "akfndkwfnklswnmljkfnmswljkfnwjlkngfjwenj"
database:
  host: localhost
  port: 3306
  user: root
  pass: tongminh1510
  dbname: EDUDBTEST