server:
  host: 127.0.0.1
  port: 8081
  timeout:
    server: "30s"
    read: "15s"
    write: "10s"
    idle: "5s"


XApiKey: "akfndkwfnklswnmljkfnmswljkfnwjlkngfjwenj"
database:
  host: mysql-242e090-ducminhtong1510-d931.a.aivencloud.com
  port: 21440
  user: avnadmin
  pass: AVNS_PRb_ApuInzGLCBw_ux7
  dbName: defaultdb
